---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
            args: [--remove]
          - id: check-yaml
          - id: check-shebang-scripts-are-executable
          - id: debug-statements
            language_version: python3
          - id: check-json
    - repo: https://github.com/PyCQA/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            name: pydocstyle (application)
            args: ["--convention=pep257", "--add-ignore=D100,D104,D107"]
            language_version: python3
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.2
      hooks:
          - id: autopep8
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.4
      hooks:
      - id: bandit
        args: ["--skip=B314,B405,B406,B410"]
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
      - id: isort
        args: [--filter-files]
        files: \.py$
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          language_version: python3
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.0.1
      hooks:
        - id: mypy
          language_version: python3.9
    - repo: https://github.com/rstcheck/rstcheck
      rev: "v6.1.1"  # released versions are too old
      hooks:
      - id: rstcheck
        args: ["--ignore-messages", 'Duplicate implicit target.*|No directive entry for|Hyperlink target ".*" is not referenced.']
        exclude: LICENSE.txt
        types: [file]
        files: \.rst$
        additional_dependencies: [Sphinx]
