#!/usr/bin/env python

import ConfigParser
import os
import sys

def get_executable():
    configdir = os.path.expanduser('~/.gtimelog')
    settings_file = os.path.join(configdir, 'gtimelogrc')
    config = ConfigParser.RawConfigParser()
    config.read([settings_file])
    return config.get('gtimelog.app', 'python') or "/opt/local/bin/python2.5"

execdir = os.path.dirname(sys.argv[0])
executable = get_executable()
resdir = os.path.join(os.path.dirname(execdir), "Resources")
libdir = os.path.join(os.path.dirname(execdir), "Frameworks")
mainprogram = os.path.join(resdir, "__argvemulator_gtimelog.py")

sys.argv.insert(1, mainprogram)
if 0 or 0:
    os.environ["PYTHONPATH"] = resdir
    if 0:
        os.environ["PYTHONHOME"] = resdir
else:
    pypath = os.getenv("PYTHONPATH", "")
    if pypath:
        pypath = ":" + pypath
    os.environ["PYTHONPATH"] = resdir + pypath
os.environ["PYTHONEXECUTABLE"] = executable
os.environ["DYLD_LIBRARY_PATH"] = libdir
os.environ["DYLD_FRAMEWORK_PATH"] = libdir
os.execve(executable, sys.argv, os.environ)
